require("control")
require("prototypes.category")
require("prototypes.tree")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.ammo")
require("prototypes.entity")
require("prototypes.technology")
